[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "https://weather-claus.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200